# arithmetic operations
a=np.arange(9,dtype=np.int_).reshape(3,3)
print("first array")
print(a)
print("second array")
b=np.array([10,10,10])
print(b)
print('add the two  arrays')
print(np.add(a,b))
print('subtract the two arrays')
print(np.subtract(a,b))
print('multiply the two arrays')
print(np.multiply(a,b))
print('after divide')
print(np.divide(a,b))
print('Dot product two arrays')
print(np.dot(a,b))
print(np.sum(a))
print(np.max(a))
print(np.var(a))
